export const DEAL_STATES = {
  REQUIREMENT_CREATED: 'REQUIREMENT_CREATED',
  SELLER_VERIFIED: 'SELLER_VERIFIED',
  SELLER_LOCKED: 'SELLER_LOCKED',
  BROADCASTED: 'BROADCASTED',
  BUYER_TOKEN_RECEIVED: 'BUYER_TOKEN_RECEIVED',
  PICKUP_SCHEDULED: 'PICKUP_SCHEDULED',
  PICKED_UP: 'PICKED_UP',
  DELIVERED: 'DELIVERED',
  SETTLED: 'SETTLED',
  CLOSED: 'CLOSED',
  CANCELLED: 'CANCELLED'
};

export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  ESCROWED: 'ESCROWED',
  RELEASED: 'RELEASED',
  FAILED: 'FAILED'
};

export const ROLES = {
  ADMIN: 'ADMIN',
  OPERATOR: 'OPERATOR',
  BROKER: 'BROKER',
  LOGISTICS: 'LOGISTICS'
};
